using System.Globalization;
using System.Text;

namespace TokkDb.Assistant.TokenBudget.Harness;

/// <summary>The table §6.3 asks for: every figure of §6.2a beside its limit, per scenario, with the run count behind every rate.</summary>
public static class Report
{
    public static string Markdown(IReadOnlyList<ScenarioMeasurement> measurements, string model, string mode, string machine, DateTimeOffset when, bool probed)
    {
        var text = new StringBuilder();
        text.AppendLine("# Assistant token budget");
        text.AppendLine();
        text.AppendLine($"Measured {when:yyyy-MM-dd HH:mm} on {machine}, model `{model}`, {mode}. Generated by `dotnet run --project TokkDb.Assistant.TokenBudget -- measure`; do not edit by hand.");
        text.AppendLine();
        text.AppendLine(probed
            ? "Prompt tokens are the single-token probe's figure (§6.2a): the same prompt sent once more with the output capped at one token, because Ollama's `prompt_tokens` on a working call is unreliable after a generation that filled the context."
            : "Prompt tokens are the fake model's estimate of the prompt it was sent; the fake never fills a window, so the figures here are the structure of each scenario, not the real model's cost.");
        text.AppendLine();

        foreach (var measurement in measurements)
        {
            var limits = measurement.Limits;
            text.AppendLine($"## {limits.Scenario} · {limits.Title}");
            text.AppendLine();
            text.AppendLine($"Says: *{ScenarioRunner.Said(limits.Scenario)}*");
            text.AppendLine();
            text.AppendLine("| figure | measured | limit | |");
            text.AppendLine("|---|---:|---:|---|");
            Row(text, "prompt tokens (max over runs)", measurement.MaxPromptTokens, limits.PromptTokens);
            Row(text, "output tokens (max)", measurement.MaxOutputTokens, limits.OutputTokens);
            text.AppendLine($"| total tokens (max) | {measurement.MaxTotalTokens} | | |");
            Row(text, "model calls (max)", measurement.MaxModelCalls, limits.ModelCalls);
            Row(text, "round trips (max)", measurement.MaxRoundTrips, limits.RoundTrips);
            Row(text, "repairs (max)", measurement.MaxRetries, limits.Retries);
            Row(text, "peak context (max)", measurement.MaxPeakContext, limits.PeakContext);
            text.AppendLine($"| latency p50 / p95 | {measurement.LatencyP50.TotalSeconds.ToString("0.00", CultureInfo.InvariantCulture)}s / {measurement.LatencyP95.TotalSeconds.ToString("0.00", CultureInfo.InvariantCulture)}s | {limits.Latency.TotalSeconds.ToString("0", CultureInfo.InvariantCulture)}s | {(measurement.LatencyP95 <= limits.Latency ? "met" : "**over**")} |");
            text.AppendLine($"| success rate | {measurement.Successes}/{measurement.RunCount} = {measurement.SuccessRate.ToString("0.00", CultureInfo.InvariantCulture)}, lower bound {measurement.LowerBound.ToString("0.00", CultureInfo.InvariantCulture)} at 95% | floor {limits.SuccessFloor.ToString("0.00", CultureInfo.InvariantCulture)} over ≥ {limits.MinimumRuns} runs | {(measurement.RunCount < limits.MinimumRuns ? "**thin**" : measurement.LowerBound >= limits.SuccessFloor ? "met" : "**below**")} |");
            text.AppendLine($"| predicted from per-call rates (AG-1d) | {measurement.PredictedRate.ToString("0.00", CultureInfo.InvariantCulture)}, distance {measurement.Distance.ToString("+0.00;-0.00;0.00", CultureInfo.InvariantCulture)} | diagnostic | |");
            var modes = measurement.FailuresByMode;
            text.AppendLine($"| failures by mode | {(modes.Count == 0 ? "none" : string.Join(", ", modes.OrderBy(static entry => entry.Key).Select(static entry => $"{Words(entry.Key)} {entry.Value}")))} | | |");
            text.AppendLine();
            text.AppendLine(measurement.IsWithinBudget ? "Within budget." : "**Not within budget:** " + string.Join("; ", measurement.Breaches) + ".");
            text.AppendLine();
        }

        return text.ToString();
    }

    private static void Row(StringBuilder text, string figure, int measured, int limit) =>
        text.AppendLine($"| {figure} | {measured} | {limit} | {(measured <= limit ? "met" : "**over**")} |");

    public static string Words(FailureMode mode) => mode switch
    {
        FailureMode.MalformedRepaired => "malformed, repaired",
        FailureMode.MalformedPastBound => "malformed past the bound",
        FailureMode.EmptyReply => "empty reply",
        FailureMode.Timeout => "timeout",
        FailureMode.Refusal => "refusal",
        FailureMode.CutOff => "cut off at the output cap",
        FailureMode.WrongOutcome => "wrong outcome",
        _ => "other"
    };
}
