<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\TokkDb.Buffer\TokkDb.Buffer.csproj" />
      <ProjectReference Include="..\TokkDb.Configuration\TokkDb.Configuration.csproj" />
    </ItemGroup>

</Project>
