<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latestMajor</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TokkDb\TokkDb.csproj" />
    <ProjectReference Include="..\TokkDb.LLM.Storage\TokkDb.LLM.Storage.csproj" />
  </ItemGroup>

</Project>
