using DocumentFormat.OpenXml;
using DocumentFormat.OpenXml.Packaging;
using DocumentFormat.OpenXml.Spreadsheet;
using TokkDb.Assistant.Ingestion;
using TokkDb.Assistant.Storage;

namespace TokkDb.Assistant.Tests;

/// <summary>
/// The three things a worksheet does that a CSV file does not, and which R-5 named as the cost of
/// reading the format rather than having it read for us: text lives in a shared table, dates are
/// numbers with a formatting rule, and a row with a gap in it has no cell for the gap.
///
/// The workbooks are built here rather than checked in, so that what is being tested is visible
/// in the test instead of being a binary somebody has to open.
/// </summary>
public sealed class XlsxTests
{
    [Fact]
    public void A_workbook_is_read_one_table_per_sheet()
    {
        var workbook = Workbook.With(
            ("Expenses", new[]
            {
                new[] { "Event", "Amount" },
                ["EuroPython", "840.50"],
                ["DevDays", "600"]
            }),
            ("Reading", new[]
            {
                new[] { "Title", "Author" },
                ["Designing Data-Intensive Applications", "Kleppmann"]
            }));

        var tables = TabularFile.ReadWorkbook(workbook);

        Assert.Equal(2, tables.Count);
        Assert.Equal("Expenses", tables[0].Name);
        Assert.Equal(["Event", "Amount"], tables[0].Columns);
        Assert.Equal(2, tables[0].RowCount);

        Assert.Equal("Reading", tables[1].Name);
        Assert.Equal(["Title", "Author"], tables[1].Columns);
        Assert.Equal(1, tables[1].RowCount);
    }

    /// <summary>
    /// A sheet holds no dates. It holds a count of days from the end of 1899 and a style saying
    /// to show it as a date, so whether a cell is a date is a property of its formatting. A
    /// reader that ignored the styles would report every date in every spreadsheet as a
    /// five-digit number.
    /// </summary>
    [Fact]
    public void A_date_in_a_worksheet_is_a_number_with_a_format_and_is_read_as_a_date()
    {
        var workbook = Workbook.WithDates(
            header: ["Event", "Paid on"],
            rows:
            [
                ("EuroPython", new DateTime(2026, 7, 20)),
                ("DevDays", new DateTime(2026, 5, 14))
            ]);

        var table = Assert.Single(TabularFile.ReadWorkbook(workbook));

        Assert.Equal(["Event", "Paid on"], table.Columns);

        var paidOn = table.Profiles[1];
        Assert.Equal(ColumnType.Date, paidOn.Inferred);
        Assert.Equal("2026-05-14", paidOn.Minimum);
        Assert.Equal("2026-07-20", paidOn.Maximum);

        Assert.Equal(new DateOnly(2026, 7, 20), paidOn.Read(table.Rows[0][1]));
    }

    /// <summary>
    /// A row with nothing in the second column holds the first and the third, and only the cell
    /// references say so. Getting this wrong shifts every value after a gap one column to the
    /// left, which reads as valid data and is not.
    /// </summary>
    [Fact]
    public void A_row_with_a_gap_in_it_keeps_its_values_in_the_right_columns()
    {
        var workbook = Workbook.Sparse(
            header: ["Event", "City", "Amount"],
            // The middle cell is missing, not empty.
            present: [("A2", "EuroPython"), ("C2", "840.50")]);

        var table = Assert.Single(TabularFile.ReadWorkbook(workbook));
        var row = Assert.Single(table.Rows);

        Assert.Equal("EuroPython", row[0]);
        Assert.Null(row[1]);
        Assert.Equal("840.50", row[2]);

        Assert.Equal(1, table.Profiles[1].BlankCount);
        Assert.Equal(ColumnType.Decimal, table.Profiles[2].Inferred);
    }

    [Fact]
    public void A_preamble_in_a_worksheet_is_found_the_same_way_it_is_in_a_file()
    {
        var workbook = Workbook.With(
            ("Sheet1", new[]
            {
                new[] { "Expense report - Q3", "", "" },
                ["Generated by the finance system", "", ""],
                ["", "", ""],
                ["Event", "City", "Amount"],
                ["EuroPython", "Prague", "840.50"],
                ["DevDays", "Vilnius", "600"]
            }));

        var table = Assert.Single(TabularFile.ReadWorkbook(workbook));

        Assert.True(table.Reading.HeaderWasFound);
        Assert.Equal(["Event", "City", "Amount"], table.Columns);
        Assert.Equal(2, table.RowCount);
        Assert.Equal(4, table.Reading.HeaderLineNumber);
    }

    [Fact]
    public void An_empty_sheet_is_not_a_table()
    {
        var workbook = Workbook.With(
            ("Data", new[] { new[] { "Event" }, ["EuroPython"] }),
            ("Notes", []));

        Assert.Equal(["Data"], TabularFile.ReadWorkbook(workbook).Select(static table => table.Name));
    }

    /// <summary>Building the workbooks the tests above read.</summary>
    private static class Workbook
    {
        public static Stream With(params (string Name, string[][] Rows)[] sheets) =>
            Build(sheets.Select(static sheet =>
                (sheet.Name, sheet.Rows.Select(static row => row.Select(static cell => (object?)cell).ToArray()).ToArray())).ToArray());

        public static Stream WithDates(string[] header, (string Event, DateTime PaidOn)[] rows) =>
            Build(
            [
                ("Sheet1", new[] { header.Select(static name => (object?)name).ToArray() }
                    .Concat(rows.Select(static row => new object?[] { row.Event, row.PaidOn }))
                    .ToArray())
            ]);

        public static Stream Sparse(string[] header, (string Reference, string Value)[] present)
        {
            var stream = new MemoryStream();

            using (var document = SpreadsheetDocument.Create(stream, SpreadsheetDocumentType.Workbook, autoSave: true))
            {
                var workbook = document.AddWorkbookPart();
                workbook.Workbook = new DocumentFormat.OpenXml.Spreadsheet.Workbook();

                var worksheet = workbook.AddNewPart<WorksheetPart>();
                var data = new SheetData();

                var headerRow = new Row { RowIndex = 1 };
                for (var i = 0; i < header.Length; i++)
                {
                    headerRow.Append(Inline($"{(char)('A' + i)}1", header[i]));
                }

                data.Append(headerRow);

                var body = new Row { RowIndex = 2 };
                foreach (var (reference, value) in present) body.Append(Inline(reference, value));
                data.Append(body);

                worksheet.Worksheet = new Worksheet(data);

                workbook.Workbook.Append(new Sheets(new Sheet
                {
                    Id = workbook.GetIdOfPart(worksheet), SheetId = 1, Name = "Sheet1"
                }));
            }

            stream.Position = 0;
            return stream;
        }

        private static Stream Build((string Name, object?[][] Rows)[] sheets)
        {
            var stream = new MemoryStream();

            using (var document = SpreadsheetDocument.Create(stream, SpreadsheetDocumentType.Workbook, autoSave: true))
            {
                var workbook = document.AddWorkbookPart();
                workbook.Workbook = new DocumentFormat.OpenXml.Spreadsheet.Workbook();

                // One style that is a date and one that is not, which is the whole of what a
                // reader has to tell apart.
                var styles = workbook.AddNewPart<WorkbookStylesPart>();
                styles.Stylesheet = new Stylesheet(
                    new Fonts(new Font()),
                    new Fills(new Fill()),
                    new Borders(new Border()),
                    new CellFormats(
                        new CellFormat { NumberFormatId = 0 },
                        new CellFormat { NumberFormatId = 14, ApplyNumberFormat = true }));

                var sheetList = new Sheets();
                uint sheetId = 1;

                foreach (var (name, rows) in sheets)
                {
                    var part = workbook.AddNewPart<WorksheetPart>();
                    var data = new SheetData();

                    for (var r = 0; r < rows.Length; r++)
                    {
                        var row = new Row { RowIndex = (uint)(r + 1) };

                        for (var c = 0; c < rows[r].Length; c++)
                        {
                            var reference = $"{(char)('A' + c)}{r + 1}";

                            row.Append(rows[r][c] switch
                            {
                                DateTime moment => new Cell
                                {
                                    CellReference = reference,
                                    StyleIndex = 1,
                                    CellValue = new CellValue(moment.ToOADate().ToString(System.Globalization.CultureInfo.InvariantCulture))
                                },
                                string text => Inline(reference, text),
                                _ => new Cell { CellReference = reference }
                            });
                        }

                        data.Append(row);
                    }

                    part.Worksheet = new Worksheet(data);

                    sheetList.Append(new Sheet
                    {
                        Id = workbook.GetIdOfPart(part), SheetId = sheetId, Name = name
                    });

                    sheetId++;
                }

                workbook.Workbook.Append(sheetList);
            }

            stream.Position = 0;
            return stream;
        }

        private static Cell Inline(string reference, string text) => new()
        {
            CellReference = reference,
            DataType = CellValues.InlineString,
            InlineString = new InlineString(new Text(text))
        };
    }
}
