<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\TokkDb.Disk\TokkDb.Disk.csproj" />
      <ProjectReference Include="..\TokkDb.Documents\TokkDb.Documents.csproj" />
    </ItemGroup>

</Project>
